server:
  port: 8090

spring:
  mvc:
    view:
      prefix: /views/
      suffix: .html

  main:
    allow-bean-definition-overriding: true
  task:
    scheduling:
      enabled: true

  #  datasource:
#    name: ibookingdb
#    url: jdbc:mysql://6.tcp.cpolar.top:10550/ibooking?useSSL=false
#    username: root
#    password: 123456
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      mode: always

  mail:
    host: smtp.qq.com
    username: 1624716569@qq.com
    password: kfmthljwceksciah
    port: 587
    default-encoding: UTF-8
    properties:
      mails:
        smtp:
          ssl:
            enable: false
            required: false
        debug: true

mybatis:
  mapper-locations: classpath:com.huawei.ibooking.mapper/*.xml
  type-aliases-package: com.huawei.ibooking.model

logging:
  level:
    com.huawei.ibooking: debug
