name: auto-test

on:
  push:
    # 分支
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run tests
        run:  |
            cd ibooking-spring
            mvn test
      
      - name: Build with Maven
        run: |
            cd ibooking-spring
            mvn package -Dmaven.test.skip=true

      - name: Login to Huawei Docker
        run: docker login -u cn-east-3@${{ secrets.AK }} -p ${{secrets.KEY}} swr.cn-east-3.myhuaweicloud.com

      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d-%H-%M-%S')"

      - name: build the docker image
        run: docker build -t ibooking ./ibooking-spring

      - name: Tag docker image
        run: docker tag ibooking:latest swr.cn-east-3.myhuaweicloud.com/cloud_ibooking/ibooking:${{ steps.date.outputs.today }}

      - name: Push docker image
        run: docker push swr.cn-east-3.myhuaweicloud.com/cloud_ibooking/ibooking:${{ steps.date.outputs.today }}

      - name: build the docker image
        run: docker build -t ibooking-vue ./ibooking-vue

      - name: Tag docker image
        run: docker tag ibooking-vue:latest swr.cn-east-3.myhuaweicloud.com/cloud_ibooking/ibooking-vue:${{ steps.date.outputs.today }}

      - name: Push docker image
        run: docker push swr.cn-east-3.myhuaweicloud.com/cloud_ibooking/ibooking-vue:${{ steps.date.outputs.today }}



      